# permissions for end users to edit hbasetenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hbasetenant-editor-role
rules:
- apiGroups:
  - kvstore.flipkart.com
  resources:
  - hbasetenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvstore.flipkart.com
  resources:
  - hbasetenants/status
  verbs:
  - get
