# permissions for end users to view hbasetenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hbasetenant-viewer-role
rules:
- apiGroups:
  - kvstore.flipkart.com
  resources:
  - hbasetenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kvstore.flipkart.com
  resources:
  - hbasetenants/status
  verbs:
  - get
